name: Create-Release

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release:
    if: github.event.ref == 'refs/heads/main'
    permissions:
      contents: write  # for Git to git push
      pull-requests: write  # for actions/labeler to add labels to PRs
    
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
        with:
          egress-policy: audit
 
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha}}
          fetch-depth: 0

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          PRERELEASE: true